// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: comments.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createComment = `-- name: CreateComment :one
INSERT INTO comments (user_id, source, external_id, content, created_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, source, external_id, content, created_at
`

type CreateCommentParams struct {
	UserID     int64          `json:"user_id"`
	Source     string         `json:"source"`
	ExternalID sql.NullString `json:"external_id"`
	Content    sql.NullString `json:"content"`
	CreatedAt  time.Time      `json:"created_at"`
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error) {
	row := q.db.QueryRowContext(ctx, createComment,
		arg.UserID,
		arg.Source,
		arg.ExternalID,
		arg.Content,
		arg.CreatedAt,
	)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Source,
		&i.ExternalID,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}
