// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: mentions.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createTickerMention = `-- name: CreateTickerMention :one
INSERT INTO ticker_mentions (
  ticker_id,
  user_id,
  comment_id,
  mentioned_at,
  price_at_mention
)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, ticker_id, user_id, comment_id, mentioned_at, price_at_mention
`

type CreateTickerMentionParams struct {
	TickerID       int64         `json:"ticker_id"`
	UserID         int64         `json:"user_id"`
	CommentID      sql.NullInt64 `json:"comment_id"`
	MentionedAt    time.Time     `json:"mentioned_at"`
	PriceAtMention string        `json:"price_at_mention"`
}

func (q *Queries) CreateTickerMention(ctx context.Context, arg CreateTickerMentionParams) (TickerMention, error) {
	row := q.db.QueryRowContext(ctx, createTickerMention,
		arg.TickerID,
		arg.UserID,
		arg.CommentID,
		arg.MentionedAt,
		arg.PriceAtMention,
	)
	var i TickerMention
	err := row.Scan(
		&i.ID,
		&i.TickerID,
		&i.UserID,
		&i.CommentID,
		&i.MentionedAt,
		&i.PriceAtMention,
	)
	return i, err
}
