// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type Comment struct {
	ID         int64          `json:"id"`
	UserID     int64          `json:"user_id"`
	Source     string         `json:"source"`
	ExternalID sql.NullString `json:"external_id"`
	Content    sql.NullString `json:"content"`
	CreatedAt  time.Time      `json:"created_at"`
}

type Ticker struct {
	ID          int64          `json:"id"`
	Symbol      string         `json:"symbol"`
	CompanyName sql.NullString `json:"company_name"`
	Exchange    sql.NullString `json:"exchange"`
	Currency    string         `json:"currency"`
	CreatedAt   time.Time      `json:"created_at"`
}

type TickerMention struct {
	ID             int64         `json:"id"`
	TickerID       int64         `json:"ticker_id"`
	UserID         int64         `json:"user_id"`
	CommentID      sql.NullInt64 `json:"comment_id"`
	MentionedAt    time.Time     `json:"mentioned_at"`
	PriceAtMention string        `json:"price_at_mention"`
}

type TickerPrice struct {
	TickerID   int64     `json:"ticker_id"`
	Price      string    `json:"price"`
	RecordedAt time.Time `json:"recorded_at"`
}

type User struct {
	ID        int64     `json:"id"`
	Username  string    `json:"username"`
	CreatedAt time.Time `json:"created_at"`
}
