// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: prices.sql

package db

import (
	"context"
	"time"
)

const getLatestTickerPrice = `-- name: GetLatestTickerPrice :one
SELECT price, recorded_at
FROM ticker_prices
WHERE ticker_id = $1
ORDER BY recorded_at DESC
LIMIT 1
`

type GetLatestTickerPriceRow struct {
	Price      string    `json:"price"`
	RecordedAt time.Time `json:"recorded_at"`
}

func (q *Queries) GetLatestTickerPrice(ctx context.Context, tickerID int64) (GetLatestTickerPriceRow, error) {
	row := q.db.QueryRowContext(ctx, getLatestTickerPrice, tickerID)
	var i GetLatestTickerPriceRow
	err := row.Scan(&i.Price, &i.RecordedAt)
	return i, err
}

const insertTickerPrice = `-- name: InsertTickerPrice :exec
INSERT INTO ticker_prices (ticker_id, price, recorded_at)
VALUES ($1, $2, $3)
ON CONFLICT (ticker_id, recorded_at) DO NOTHING
`

type InsertTickerPriceParams struct {
	TickerID   int64     `json:"ticker_id"`
	Price      string    `json:"price"`
	RecordedAt time.Time `json:"recorded_at"`
}

func (q *Queries) InsertTickerPrice(ctx context.Context, arg InsertTickerPriceParams) error {
	_, err := q.db.ExecContext(ctx, insertTickerPrice, arg.TickerID, arg.Price, arg.RecordedAt)
	return err
}
