// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error)
	CreateTicker(ctx context.Context, arg CreateTickerParams) (Ticker, error)
	CreateTickerMention(ctx context.Context, arg CreateTickerMentionParams) (TickerMention, error)
	CreateUser(ctx context.Context, username string) (User, error)
	GetLatestTickerPrice(ctx context.Context, tickerID int64) (GetLatestTickerPriceRow, error)
	GetTickerBySymbol(ctx context.Context, symbol string) (Ticker, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	InsertTickerPrice(ctx context.Context, arg InsertTickerPriceParams) error
}

var _ Querier = (*Queries)(nil)
