// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"time"
)

type Querier interface {
	CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error)
	CreateTicker(ctx context.Context, arg CreateTickerParams) (TickerName, error)
	CreateTickerMention(ctx context.Context, arg CreateTickerMentionParams) (TickerMention, error)
	CreateUser(ctx context.Context, username string) (User, error)
	CreateVisitor(ctx context.Context, arg CreateVisitorParams) error
	DeleteTickerPriceByDate(ctx context.Context, arg DeleteTickerPriceByDateParams) error
	GetAllMentionsComplete(ctx context.Context, mentionedAt time.Time) ([]GetAllMentionsCompleteRow, error)
	GetAllSplits(ctx context.Context) ([]GetAllSplitsRow, error)
	GetAllVisitors(ctx context.Context, limit int32) ([]Visitor, error)
	GetCommentByUserAndExternalID(ctx context.Context, arg GetCommentByUserAndExternalIDParams) (Comment, error)
	GetSplitsBetweenDates(ctx context.Context, arg GetSplitsBetweenDatesParams) ([]GetSplitsBetweenDatesRow, error)
	GetSplitsByTicker(ctx context.Context, tickerID int64) ([]TickerSplit, error)
	GetTickerBySymbol(ctx context.Context, symbol string) (TickerName, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetUserMentionsComplete(ctx context.Context, arg GetUserMentionsCompleteParams) ([]GetUserMentionsCompleteRow, error)
	GetVisitorCountAll(ctx context.Context) (int64, error)
	GetVisitorCountLastDay(ctx context.Context) (int64, error)
	GetVisitorCountLastMonth(ctx context.Context) (int64, error)
	GetVisitorCountLastWeek(ctx context.Context) (int64, error)
	GetVisitorsByEndpoint(ctx context.Context, endpoint string) ([]Visitor, error)
	GetVisitorsByIP(ctx context.Context, ipAddress string) ([]Visitor, error)
	GetVisitorsLastDay(ctx context.Context) ([]Visitor, error)
	GetVisitorsLastMonth(ctx context.Context) ([]Visitor, error)
	GetVisitorsLastWeek(ctx context.Context) ([]Visitor, error)
	InsertTickerPrice(ctx context.Context, arg InsertTickerPriceParams) (TickerPrice, error)
	InsertTickerSplit(ctx context.Context, arg InsertTickerSplitParams) error
	ListAllTickers(ctx context.Context) ([]TickerName, error)
	UpsertTicker(ctx context.Context, arg UpsertTickerParams) error
}

var _ Querier = (*Queries)(nil)
