// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tickers.sql

package db

import (
	"context"
	"database/sql"
)

const createTicker = `-- name: CreateTicker :one
INSERT INTO tickers (symbol, company_name, exchange)
VALUES ($1, $2, $3)
RETURNING id, symbol, company_name, exchange, currency, created_at
`

type CreateTickerParams struct {
	Symbol      string         `json:"symbol"`
	CompanyName sql.NullString `json:"company_name"`
	Exchange    sql.NullString `json:"exchange"`
}

func (q *Queries) CreateTicker(ctx context.Context, arg CreateTickerParams) (Ticker, error) {
	row := q.db.QueryRowContext(ctx, createTicker, arg.Symbol, arg.CompanyName, arg.Exchange)
	var i Ticker
	err := row.Scan(
		&i.ID,
		&i.Symbol,
		&i.CompanyName,
		&i.Exchange,
		&i.Currency,
		&i.CreatedAt,
	)
	return i, err
}

const getTickerBySymbol = `-- name: GetTickerBySymbol :one
SELECT id, symbol, company_name, exchange, currency, created_at
FROM tickers
WHERE symbol = $1
`

func (q *Queries) GetTickerBySymbol(ctx context.Context, symbol string) (Ticker, error) {
	row := q.db.QueryRowContext(ctx, getTickerBySymbol, symbol)
	var i Ticker
	err := row.Scan(
		&i.ID,
		&i.Symbol,
		&i.CompanyName,
		&i.Exchange,
		&i.Currency,
		&i.CreatedAt,
	)
	return i, err
}
