// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: visitors.sql

package db

import (
	"context"
	"time"
)

const createVisitor = `-- name: CreateVisitor :exec
INSERT INTO visitors (ip_address, endpoint, visited_at)
VALUES ($1, $2, $3)
`

type CreateVisitorParams struct {
	IpAddress string    `json:"ip_address"`
	Endpoint  string    `json:"endpoint"`
	VisitedAt time.Time `json:"visited_at"`
}

func (q *Queries) CreateVisitor(ctx context.Context, arg CreateVisitorParams) error {
	_, err := q.db.ExecContext(ctx, createVisitor, arg.IpAddress, arg.Endpoint, arg.VisitedAt)
	return err
}

const getAllVisitors = `-- name: GetAllVisitors :many
SELECT id, ip_address, endpoint, visited_at
FROM visitors
ORDER BY visited_at DESC
LIMIT $1
`

func (q *Queries) GetAllVisitors(ctx context.Context, limit int32) ([]Visitor, error) {
	rows, err := q.db.QueryContext(ctx, getAllVisitors, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Visitor
	for rows.Next() {
		var i Visitor
		if err := rows.Scan(
			&i.ID,
			&i.IpAddress,
			&i.Endpoint,
			&i.VisitedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVisitorCountAll = `-- name: GetVisitorCountAll :one
SELECT COUNT(*) as count
FROM visitors
`

func (q *Queries) GetVisitorCountAll(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getVisitorCountAll)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getVisitorCountLastDay = `-- name: GetVisitorCountLastDay :one
SELECT COUNT(*) as count
FROM visitors
WHERE visited_at >= NOW() - INTERVAL '1 day'
`

func (q *Queries) GetVisitorCountLastDay(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getVisitorCountLastDay)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getVisitorCountLastMonth = `-- name: GetVisitorCountLastMonth :one
SELECT COUNT(*) as count
FROM visitors
WHERE visited_at >= NOW() - INTERVAL '1 month'
`

func (q *Queries) GetVisitorCountLastMonth(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getVisitorCountLastMonth)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getVisitorCountLastWeek = `-- name: GetVisitorCountLastWeek :one
SELECT COUNT(*) as count
FROM visitors
WHERE visited_at >= NOW() - INTERVAL '1 week'
`

func (q *Queries) GetVisitorCountLastWeek(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getVisitorCountLastWeek)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getVisitorsByEndpoint = `-- name: GetVisitorsByEndpoint :many
SELECT id, ip_address, endpoint, visited_at
FROM visitors
WHERE endpoint = $1
ORDER BY visited_at DESC
`

func (q *Queries) GetVisitorsByEndpoint(ctx context.Context, endpoint string) ([]Visitor, error) {
	rows, err := q.db.QueryContext(ctx, getVisitorsByEndpoint, endpoint)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Visitor
	for rows.Next() {
		var i Visitor
		if err := rows.Scan(
			&i.ID,
			&i.IpAddress,
			&i.Endpoint,
			&i.VisitedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVisitorsByIP = `-- name: GetVisitorsByIP :many
SELECT id, ip_address, endpoint, visited_at
FROM visitors
WHERE ip_address = $1
ORDER BY visited_at DESC
`

func (q *Queries) GetVisitorsByIP(ctx context.Context, ipAddress string) ([]Visitor, error) {
	rows, err := q.db.QueryContext(ctx, getVisitorsByIP, ipAddress)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Visitor
	for rows.Next() {
		var i Visitor
		if err := rows.Scan(
			&i.ID,
			&i.IpAddress,
			&i.Endpoint,
			&i.VisitedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVisitorsLastDay = `-- name: GetVisitorsLastDay :many
SELECT id, ip_address, endpoint, visited_at
FROM visitors
WHERE visited_at >= NOW() - INTERVAL '1 day'
ORDER BY visited_at DESC
`

func (q *Queries) GetVisitorsLastDay(ctx context.Context) ([]Visitor, error) {
	rows, err := q.db.QueryContext(ctx, getVisitorsLastDay)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Visitor
	for rows.Next() {
		var i Visitor
		if err := rows.Scan(
			&i.ID,
			&i.IpAddress,
			&i.Endpoint,
			&i.VisitedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVisitorsLastMonth = `-- name: GetVisitorsLastMonth :many
SELECT id, ip_address, endpoint, visited_at
FROM visitors
WHERE visited_at >= NOW() - INTERVAL '1 month'
ORDER BY visited_at DESC
`

func (q *Queries) GetVisitorsLastMonth(ctx context.Context) ([]Visitor, error) {
	rows, err := q.db.QueryContext(ctx, getVisitorsLastMonth)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Visitor
	for rows.Next() {
		var i Visitor
		if err := rows.Scan(
			&i.ID,
			&i.IpAddress,
			&i.Endpoint,
			&i.VisitedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVisitorsLastWeek = `-- name: GetVisitorsLastWeek :many
SELECT id, ip_address, endpoint, visited_at
FROM visitors
WHERE visited_at >= NOW() - INTERVAL '1 week'
ORDER BY visited_at DESC
`

func (q *Queries) GetVisitorsLastWeek(ctx context.Context) ([]Visitor, error) {
	rows, err := q.db.QueryContext(ctx, getVisitorsLastWeek)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Visitor
	for rows.Next() {
		var i Visitor
		if err := rows.Scan(
			&i.ID,
			&i.IpAddress,
			&i.Endpoint,
			&i.VisitedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
